# Autogenerated! DO NOT EDIT!
# This justfile is autogenerated via https://std.divnix.com/reference/lib/cfg/just.html
# It can be used without Nix by running a locally installed  `just` binary.
# NOTE: Without Nix, you are responsible for having all task dependencies
# available locally!

# Uploads the build to cachix
cachix-push:
    nix build .\#x86_64-linux.kernels.packages.jupyenv --json | jq -r '.[].outputs | to_entries[].value' | cachix push gtrunsec

# Formats all changed source files
fmt:
    treefmt $(git diff --name-only --cached)

# generating configFiles with devshell
generator:
    nix develop .\#generator -c echo generating configFiles
