# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  quarto = {
    pname = "quarto";
    version = "v1.3.276";
    src = fetchFromGitHub ({
      owner = "quarto-dev";
      repo = "quarto-cli";
      rev = "v1.3.276";
      fetchSubmodules = false;
      sha256 = "sha256-ROF/kJ1D8FQJxzoBZQCDZ7IJzBbfAvFnjwd+m4ZEhXw=";
    });
  };
}
